name: metabo

services:
  app:
    image: app
    ports:
      - "20688:20688"
    volumes:
      - ${PWD}/R:/home/R
      - ${PWD}/data:/home/data
      - ${PWD}/brand:/home/brand
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped